---
language: python
python:
  - "3.7"
  - "3.8"
env:
  - ANSIBLE_PIP='ansible'
  - ANSIBLE_PIP='ansible==2.9.*'
  - ANSIBLE_PIP='ansible==2.10.*'

jobs:
  fast_finish: true

  allow_failures:
    - env: ANSIBLE_PIP='ansible==2.10.*'

dist: focal

addons:
  apt:
    packages:
      - python3-pip

install:
  - pip install "$ANSIBLE_PIP"
  - pip install yamllint

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - "find . -name '*.yml' -print0 | xargs -0 yamllint -c galaxy-yamllint.yaml"
  - cd tests; ansible-playbook test.yml -i inventory --syntax-check
  - cd tests; ./run_tests.sh
  - sudo journalctl -u demo-haproxy.service
  - sudo cat /etc/demo-haproxy/demo-haproxy.cfg

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
