---
#
# tasks file for ansible-role-set_server_timezone
#
# vim:et:ts=2:ft=ansible

- name: Set Timezone
  command: "timedatectl set-timezone {{ _set_server_timezone.timezone }}"
  changed_when: false
